exclude_paths:
  - mannheim/old/
  - stuttgart/stuttgart_old2018/
  - stuttgart/stuttgart_old2020/
engines:
  bandit:
    enabled: true
  duplication:
    enabled: false
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      # Disable "Module level import not at top of file"
      E402:
        enabled: false
      # Disable "Line too long"
      E501:
        enabled: false
  radon:
    enabled: true
  sonar-python:
    enabled: true
    checks:
      # Disable  "Rename function to match the regular expression ^[a-z_][a-z0-9_]{2,}$"
      python:S1542:
        enabled: false
