exclude_paths:
  - stuttgart/stuttgart_old/
  - gps/_testdata
engines:
  bandit:
    enabled: true
  duplication:
    enabled: false
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      # Disable "Line too long"
      E501:
        enabled: false 
  radon:
    enabled: true
  sonar-python:
    enabled: true
