name: Test xml meta and feeds

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nose
    - name: Test with nose
      run: nosetests
      env:
        HEIDELBERG_AUTH: ${{ secrets.HEIDELBERG_AUTH }}
        MANNHEIM_AUTH: ${{ secrets.MANNHEIM_AUTH }}
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        LUXEMBOURG_PROXY: ${{ secrets.LUXEMBOURG_PROXY }}
